name: Build Images

on:
  push:
    branches:
      - 'trunk'
      - 'develop'

jobs:
  Build_PHP:
    strategy:
      matrix:
        version: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0']
    environment:
      name: Build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/trunk' }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: PHP_VERSION=${{ matrix.version }} BASE_IMAGE=${{ secrets.BASE_IMAGE }}
          tags: ${{ secrets.IMAGE_NAME }}:${{ matrix.version }}-ubuntu
  Build_Dev_Image:
    strategy:
      matrix:
        version: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0']
    environment:
      name: Build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/develop' }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: PHP_VERSION=${{ matrix.version }} BASE_IMAGE=${{ secrets.BASE_IMAGE }}
          tags: ${{ secrets.IMAGE_NAME }}:${{ matrix.version }}-ubuntu-dev
